server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging.level:
  org.apache.zookeeper.ClientCnxn: WARN

management:
  security:
    enabled: false

#spring.cloud.zookeeper.dependencies:
#  - testZookeeperApp: ~