server:
  port: 8899


---
spring:
  profiles: prod
server:
  port: 8088

---
spring.profiles: prod1
spring:
  profiles:
    include:
      -prod
server:
  port: 8089

---
spring.profiles: prod2
spring:
  profiles:
    include:
      -prod